routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/auth', function () {
    return view('login');
})->name('auth');

Route::get('/signup', function () {
    return view('account');
})->name('signup');

Route::get('/', 'WelcomeController@index')->name('welcome');

Route::view('/createAccount', 'createAccount');
Route::view('/qui-sommes-nous', 'qui-sommes-nous');
Route::view('/nos-solutions', 'nos-solutions');
Route::view('/actualite', 'actualite');
Route::view('/contact', 'contact')->name('contact-me');

Auth::routes();

Route::view('/login', 'login')->name('login');

Route::get('/home', 'HomeController@index')->middleware('auth')->name('home');

Route::post('/home', 'HomeController@store_comment')->middleware('auth')->name('home.post');

Route::post('/home/reply', 'homecontroller@reply_comment')->middleware('auth')->name('home.reply');

Route::post('/home/reply', 'HomeController@reply_comment')->middleware('auth')->name('home.reply');

Route::get('/home/rex_communauty/{n}', 'HomeController@rex')->middleware('auth')->name('home.rex');

Route::post('/idea','UserController@idea')->name('idea');
Route::post('/learning','UserController@learning')->name('learning');
Route::post('/contact','UserController@contact')->name('contacter');

Route::get('/validation_verification_auth_by_email/{token}/confirmation=yes','UserController@validation')->name('validate');

Route::post('/file','PostController@file')->name('post.file');

Route::get('/formation', 'WelcomeController@formation')->name('welcome.formation');
Route::get('/support', 'WelcomeController@support')->name('welcome.support');
Route::get('/nousContacter', 'WelcomeController@contact')->name('welcome.contact');
Route::get('/notation', 'WelcomeController@notation')->name('welcome.notation');

Route::post('/contribution','WelcomeController@warning')->name('warning');

Route::get('/home/exception', 'HomeController@exception_large')->middleware('auth')->name('home_exception_large');

Route::get('/veille', 'HomeController@watch')->middleware('auth')->name('watch');

Route::get('/communication', function () {
    $events = DB::Table('events')
                ->select('events.*')
                ->where('events.day', '>=', now())
                ->orderBy('events.day')
                ->get();

    $product = DB::Table('products')
                ->select('products.*', 'enterprises.enterprise')
                ->join('enterprises', 'products.user_id', 'enterprises.user_id')
                ->first();

    $post_user_count = DB::Table('posts')
                    ->where('posts.user_id', Auth::id())
                    ->count();
    return view('plateforme.fabriquant.communication',compact($events,$product,$post_user_count));
});

Route::view('/communication', 'plateforme/fabriquant/communication');
Route::view('/publicationOffre', 'plateforme/fabriquant/publierUneOfrre');
Route::view('/webinar', 'plateforme/fabriquant/webinar');
Route::get('/notation', 'WelcomeController@note')->name('welcome.notation');
Route::view('/etudeDeMarche', 'plateforme/fabriquant/etudeDeMarche');


//Resources
Route::resource('comments', 'CommentController')->middleware('isAdmin');

Route::resource('responseComments', 'Response_commentsController')->middleware('isAdmin');

Route::resource('files', 'FileController')->middleware('isAdmin');

Route::resource('users', 'UserController');

Route::get('/users', 'UserController@index')->name('users.index')->middleware('isAdmin');
Route::get('/users/create', 'UserController@create')->name('users.create')->middleware('isAdmin');
Route::get('/users/{user}', 'UserController@show')->name('users.show')->middleware('isAdmin');
Route::get('/users/{user}/edit', 'UserController@edit')->name('users.edit')->middleware('isAdmin');
Route::delete('/users/{user}', 'UserController@destroy')->name('users.destroy')->middleware('isAdmin');


Route::resource('posts', 'PostController');

Route::get('/posts', 'PostController@index')->name('posts.index')->middleware('isAdmin');
Route::get('/posts/create', 'PostController@create')->name('posts.create')->middleware('isAdmin');
Route::get('/posts/{post}', 'PostController@show')->name('posts.show')->middleware('isAdmin');
Route::get('/posts/{post}/edit', 'PostController@edit')->name('posts.edit')->middleware('isAdmin');
Route::delete('/posts/{post}', 'PostController@destroy')->name('posts.destroy')->middleware('isAdmin');

Route::resource('reactions', 'ReactionController');  

Route::get('/reactions', 'ReactionController@index')->name('reactions.index')->middleware('isAdmin');
Route::get('/reactions/create', 'ReactionController@create')->name('reactions.create')->middleware('isAdmin');
Route::get('/reactions/{post}', 'ReactionController@show')->name('reactions.show')->middleware('isAdmin');
Route::get('/reactions/{reaction}/edit', 'ReactionController@edit')->name('reactions.edit')->middleware('isAdmin');
Route::delete('/reactions/{reaction}', 'ReactionController@destroy')->name('reactions.destroy')->middleware('isAdmin');

Route::resource('employees', 'EmployeeController')->middleware('isAdmin');

Route::resource('enterprises', 'EnterpriseController')->middleware('isAdmin');

Route::resource('events', 'EventController')->middleware('isAdmin');

Route::resource('products', 'ProductController')->middleware('isAdmin');


Route::resource('advertisements', 'advertisementController')->middleware('isAdmin');

Route::resource('announces', 'announceController')->middleware('isAdmin');

app/Models/Response_comment.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class response_comments
 * @package App\Models
 * @version August 23, 2021, 5:00 pm UTC
 *
 * @property string value
 * @property string fullname
 * @property integer user_id
 * @property integer comment_id
 */
class Response_comment extends Model
{
    use SoftDeletes;

    public $table = 'response_comments';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'value',
        'fullname',
        'user_id',
        'comment_id',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'value' => 'string',
        'fullname' => 'string',
        'user_id' => 'integer',
        'comment_id' => 'integer',

    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/Response_commentsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Createresponse_commentsRequest;
use App\Http\Requests\Updateresponse_commentsRequest;
use App\Http\Controllers\AppBaseController;
use App\Models\Response_comment;
use Illuminate\Http\Request;
use Flash;
use Response;

class Response_commentsController extends AppBaseController
{
    /**
     * Display a listing of the response_comments.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        /** @var response_comments $responseComments */
        $responseComments = Response_comment::all();

        return view('response_comments.index')
            ->with('responseComments', $responseComments);
    }

    /**
     * Show the form for creating a new response_comments.
     *
     * @return Response
     */
    public function create()
    {
        return view('response_comments.create');
    }

    /**
     * Store a newly created response_comments in storage.
     *
     * @param Createresponse_commentsRequest $request
     *
     * @return Response
     */
    public function store(Createresponse_commentsRequest $request)
    {
        $input = $request->all();

        /** @var response_comments $responseComments */
        $responseComment = Response_comment::create($input);

        $responseComments =  DB::Table('users')->select('employees.firstName', 'employees.lastName', 'users.photo' ,'comments.value')
        ->join('employees', 'users.id', 'employees.user_id')
        ->join('comments', 'users.id', 'comments.user_id')
        ->where('comments.post_id', $request->post_id)
        ->get();
        Flash::success('Response Comments saved successfully.');

        return redirect(route('responseComments.index'));
    }

    /**
     * Display the specified response_comments.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        /** @var response_comments $responseComments */
        $responseComments = Response_comment::find($id);

        if (empty($responseComments)) {
            Flash::error('Response Comments not found');

            return redirect(route('responseComments.index'));
        }

        return view('response_comments.show')->with('responseComments', $responseComments);
    }

    /**
     * Show the form for editing the specified response_comments.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        /** @var response_comments $responseComments */
        $responseComments = Response_comment::find($id);

        if (empty($responseComments)) {
            Flash::error('Response Comments not found');

            return redirect(route('responseComments.index'));
        }

        return view('response_comments.edit')->with('responseComments', $responseComments);
    }

    /**
     * Update the specified response_comments in storage.
     *
     * @param int $id
     * @param Updateresponse_commentsRequest $request
     *
     * @return Response
     */
    public function update($id, Updateresponse_commentsRequest $request)
    {
        /** @var response_comments $responseComments */
        $responseComments = Response_comment::find($id);

        if (empty($responseComments)) {
            Flash::error('Response Comments not found');

            return redirect(route('responseComments.index'));
        }

        $responseComments->fill($request->all());
        $responseComments->save();

        Flash::success('Response Comments updated successfully.');

        return redirect(route('responseComments.index'));
    }

    /**
     * Remove the specified response_comments from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        /** @var response_comments $responseComments */
        $responseComments = Response_comment::find($id);

        if (empty($responseComments)) {
            Flash::error('Response Comments not found');

            return redirect(route('responseComments.index'));
        }

        $responseComments->delete();

        Flash::success('Response Comments deleted successfully.');

        return redirect(route('responseComments.index'));
    }
}

resources/views/response_comments/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Response Comments
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'responseComments.store']) !!}

                        @include('response_comments.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/response_comments/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Response Comments
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($responseComments, ['route' => ['responseComments.update', $responseComments->id], 'method' => 'patch']) !!}

                        @include('response_comments.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/response_comments/fields.blade.php
<!-- Value Field -->
<div class="form-group col-sm-6">
    {!! Form::label('value', 'Value:') !!}
    {!! Form::text('value', null, ['class' => 'form-control']) !!}
</div>

<!-- Fullname Field -->
<div class="form-group col-sm-6">
    {!! Form::label('fullname', 'Fullname:') !!}
    {!! Form::text('fullname', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('responseComments.index') }}" class="btn btn-default">Cancel</a>
</div>

resources/views/response_comments/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Response Comments</h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('response_comments.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/response_comments/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Response Comments
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('response_comments.show_fields')
                    <a href="{{ route('responseComments.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/response_comments/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{{ $responseComments->id }}</p>
</div>

<!-- Value Field -->
<div class="form-group">
    {!! Form::label('value', 'Value:') !!}
    <p>{{ $responseComments->value }}</p>
</div>

<!-- Fullname Field -->
<div class="form-group">
    {!! Form::label('fullname', 'Fullname:') !!}
    <p>{{ $responseComments->fullname }}</p>
</div>

<!-- User Id Field -->
<div class="form-group">
    {!! Form::label('user_id', 'User Id:') !!}
    <p>{{ $responseComments->user_id }}</p>
</div>

<!-- Comment Id Field -->
<div class="form-group">
    {!! Form::label('comment_id', 'Comment Id:') !!}
    <p>{{ $responseComments->comment_id }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $responseComments->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $responseComments->updated_at }}</p>
</div>

resources/views/response_comments/table.blade.php
<div class="table-responsive">
    <table class="table" id="responseComments-table">
        <thead>
            <tr>
                <th>Value</th>
        <th>Fullname</th>
        <th>User Id</th>
        <th>Comment Id</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($responseComments as $responseComments)
            <tr>
                <td>{{ $responseComments->value }}</td>
            <td>{{ $responseComments->fullname }}</td>
            <td>{{ $responseComments->user_id }}</td>
            <td>{{ $responseComments->comment_id }}</td>
                <td>
                    {!! Form::open(['route' => ['responseComments.destroy', $responseComments->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('responseComments.show', [$responseComments->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{{ route('responseComments.edit', [$responseComments->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>